### PR TITLE
Jni fix

### PR DESCRIPTION
**Pull request by aW4KeNiNG**
Callbacks to Android didn't work.

### CODE REVIEW

**Comment by DanielUranga** [comment]
Tested on legacy and callbacks are working ok on Android.

**Comment by aW4KeNiNG** [comment]
It doesn't work with OpenFL 3.3.x, with or without legacy.

The log error is:

> JNI.hx:177: onCallback - unknown field onURLChanging
> JNI.hx:177: onCallback - unknown field onClose

**Comment by DanielUranga** [comment]
OpenFL 3.3.3, Lime 2.6.2, using -Dlegacy. Test code is:

```
extension.webview.WebView.onURLChanging = function(x) trace("Url change: " + x);
extension.webview.WebView.onClose = function() trace("onClose");
extension.webview.WebView.open("http://www.google.com", true, null, ['(http|https)://(.*)facebook.com(.*)']);
```

**Comment by aW4KeNiNG** [comment]
Ok, it works for me with your code, and i saw the problem with my code. The functions were private, not public. With public functions works fine.

Thanks.

**Pull request closed without merging**
